package com.LC.LaraCulturaCommunity.model;
// Generated Dec 19, 2022, 2:57:24 AM by Hibernate Tools 4.3.6.Final


import lombok.*;



import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.web.multipart.MultipartFile;

/**
 * Episode generated by hbm2java
 */
@Setter
@Getter
@AllArgsConstructor
@ToString
@NoArgsConstructor
@Entity
@Table(name = "episode", catalog = "laracultura", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Episode extends BaseEntity {
	@Id
    @GeneratedValue(strategy= GenerationType.AUTO,generator="native")
    @GenericGenerator(name = "native",strategy = "native")
	@Column(name = "id_ep", unique = true, nullable = false)
	private Integer idEp;


	// @NotBlank(message = "khtar ina event ransitih")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article", nullable = false)
	private Article article;

	// @NotBlank(message = "nsiti Title")
	private String title;

	// @NotBlank(message = "describi bl english had l ivint")
	@Column(name = "description_eng")
	private String descriptionEng;

	// @NotBlank(message = "ach 3andek mat9ol 3la had l episode bl3arbiya llahykhelik")
	@Column(name = "description_ar")
	private String descriptionAr;

	
	private byte[] photo;


	@Transient
	MultipartFile image;


}
