package com.LC.LaraCulturaCommunity.model;
// Generated Dec 19, 2022, 2:57:24 AM by Hibernate Tools 4.3.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import lombok.Data;

/**
 * Roles generated by hbm2java
 */
@Data
@Entity
@Table(name = "roles")
public class Roles extends BaseEntity {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	private Integer roleId;

	@Column(name = "role_name", nullable = false, length = 50)
	private String roleName;

}
